// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gplavyckdopjftykrsfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwbGF2eWNrZG9wamZ0eWtyc2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NzgzNjEsImV4cCI6MjA2OTI1NDM2MX0.63SMFi3vp-MfmWTTxQOLvKKVfmrnIdddT9eVXcX_kiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});